# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0004_beacon_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='macAddress',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='uuid',
        ),
        migrations.AddField(
            model_name='attendee',
            name='app_version',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendee',
            name='device_type',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='ibeacon_uuid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='major_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='minor_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
