# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0006_auto_20160217_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='ID',
            new_name='corpId',
        ),
    ]
