# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0007_auto_20160217_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='macAddress',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
