# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0009_auto_20160224_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='macAddress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
