# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hac', '0011_auto_20160311_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='imageUrl',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
